### ISSUE TITLE
ImportError: libgmpxx.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by artfawl** [google-deepmind/envlogger#11]
Hello! I have an ImportError when I try to import envlogger. I get this error on my computer and in GoogleColab notebook. How can I resolve it?

**Comment by kenjitoyama** [comment]
Hello @artfawl, since compiling GMP from source via Blaze isn't supported, we rely on it being installed on the target  system. Please see here: https://github.com/google-deepmind/envlogger?tab=readme-ov-file#compiling-from-source

In Colab, you'll still need GMP in place, and you can easily install it with: `!apt install libgmp-dev`.

I was able to reproduce your error without installing GMP, and after installing it and `!pip install envlogger`, I'm able to do `import envlogger` with no problems.

Let me know if this works for you, and if it does, please close the issue. Thanks!

**Comment by artfawl** [comment]
yeah, that worked, thank you
